# version: "3.7"

# volumes:
#   db-store:
# networks:
#   network-app:
#     driver: bridge

services:
  # db:
  #   container_name: db-app
  #   image: mariadb:latest
  #   restart: unless-stopped
  #   environment:
  #     MARIADB_ROOT_PASSWORD: app
  #     MARIADB_DATABASE: db_app
  #     MARIADB_USER: root
  #     MARIADB_PASSWORD: app
  #   volumes:
  #     - ./docker/mysql/conf.d:/etc/mysql/conf.d
  #     - db-store:/var/lib/mysql
  #   networks:
  #     - network-app
    # app:
    #   container_name: app-app
    #   restart: unless-stopped
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   volumes:
    #     - ./:/var/www
    #     - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    #   networks:
    #     - network-app

    app:
      build:
        args:
          user: thitrungtinhledangkhoa
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: duantotnghiepbe
      container_name: be-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - travellist

    nginx:
      image: nginx:alpine
      container_name: nginx-service
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ./:/var/www
        - ./docker/nginx:/etc/nginx/conf.d/
        # - ./docker/nginx/conf.d/default.conf:/etc/nginx/travellist.conf
      networks:
        - travellist

networks:
  travellist:
    driver: bridge
      # depends_on:
      #   - app
  # phpmyadmin:
  #   platform: linux/x86_64
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   depends_on:
  #     - db
  #   ports:
  #     - 91:80
  #   environment:
  #     PMA_PORT: 3306
  #     PMA_HOST: db
  #   networks:
  #     - network-app
